package exception_example;

public class RunTimeException {

	public static void main(String[] args) {
		
	//	int x = 10;
	//	System.out.println(x/y);
		
		int x1 = 10;
		int y1 = 0;
		
		try {
			System.out.println(x1/y1);
		} catch(ArithmeticException e) {
			
			System.out.println("exception wae thrown ");
		}
		
		
System.out.println("22222222222222222222");
System.out.println("22222222222222222222");
System.out.println("22222222222222222222");
System.out.println("22222222222222222222");
System.out.println("22222222222222222222");
System.out.println("end of application");
		

	
	
		
		
	}	
		
		
}	
		
		
		
		
		
		
		
	
	
	//public static int dividNums(int a,int b) {
		//return a/b;
		

	
	
	
	
	

